services:
  - type: web
    name: ontario-energy-explorer
    runtime: docker
    plan: free
    rootDir: energy-explorer
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
